# Generated by Django 4.0 on 2022-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], db_index=True, default='inactive', max_length=15, verbose_name='status'),
        ),
    ]
